/**
 * @file Version.h
 * @brief Version information for RV3032.
 *
 * This file is AUTO-GENERATED by scripts/generate_version.py from library.json.
 * DO NOT EDIT MANUALLY. Update version metadata via library.json or
 * scripts/generate_version.py bump/set commands.
 */

#pragma once

#include <stdint.h>

#ifndef RV3032_VERSION_STRING
#define RV3032_VERSION_STRING "1.3.0"
#endif

#ifndef RV3032_BUILD_DATE
#define RV3032_BUILD_DATE __DATE__
#endif

#ifndef RV3032_BUILD_TIME
#define RV3032_BUILD_TIME __TIME__
#endif

#ifndef RV3032_BUILD_TIMESTAMP
#define RV3032_BUILD_TIMESTAMP RV3032_BUILD_DATE " " RV3032_BUILD_TIME
#endif

#ifndef RV3032_GIT_COMMIT
#define RV3032_GIT_COMMIT "unknown"
#endif

#ifndef RV3032_GIT_STATUS
#define RV3032_GIT_STATUS "unknown"
#endif

#ifndef RV3032_VERSION_FULL
#define RV3032_VERSION_FULL RV3032_VERSION_STRING " (" RV3032_GIT_COMMIT ", " RV3032_BUILD_TIMESTAMP ", " RV3032_GIT_STATUS ")"
#endif

namespace RV3032 {

/// @brief Major version (breaking changes).
static constexpr uint16_t VERSION_MAJOR = 1;

/// @brief Minor version (backward-compatible features).
static constexpr uint16_t VERSION_MINOR = 3;

/// @brief Patch version (backward-compatible fixes).
static constexpr uint16_t VERSION_PATCH = 0;

/// @brief Full semantic version string.
static constexpr const char* VERSION = RV3032_VERSION_STRING;

/// @brief Encoded version for numeric comparison: MAJOR*10000 + MINOR*100 + PATCH.
static constexpr uint32_t VERSION_CODE = 10300;

/// @brief Backward-compatible alias used by older repositories.
static constexpr int VERSION_INT = 10300;

/// @brief Build date string.
static constexpr const char* BUILD_DATE = RV3032_BUILD_DATE;

/// @brief Build time string.
static constexpr const char* BUILD_TIME = RV3032_BUILD_TIME;

/// @brief Build timestamp string.
static constexpr const char* BUILD_TIMESTAMP = RV3032_BUILD_TIMESTAMP;

/// @brief Git commit string.
static constexpr const char* GIT_COMMIT = RV3032_GIT_COMMIT;

/// @brief Git working tree status string.
static constexpr const char* GIT_STATUS = RV3032_GIT_STATUS;

/// @brief Full version string with build metadata.
static constexpr const char* VERSION_FULL = RV3032_VERSION_FULL;

}  // namespace RV3032
